use etwin_core::hammerfest::{HammerfestItemId, HammerfestQuestId};
use once_cell::sync::Lazy;
use std::collections::HashMap;

pub struct HammerfestQuest {
  pub id: HammerfestQuestId,
  pub title_fr: &'static str,
  pub title_en: &'static str,
  pub title_es: &'static str,
}

impl HammerfestQuest {
  const unsafe fn new_unchecked(
    id: u8,
    title_fr: &'static str,
    title_en: &'static str,
    title_es: &'static str,
  ) -> Self {
    Self {
      id: HammerfestQuestId::new_unchecked(id),
      title_fr,
      title_en,
      title_es,
    }
  }
}

#[rustfmt::skip]
pub const QUESTS: [HammerfestQuest; 76] = unsafe {
  [
    HammerfestQuest::new_unchecked(0, "Les constellations", "Constellations", "Las constelaciones"),
    HammerfestQuest::new_unchecked(1, "Mixtures du zodiaque", "Zodiac mixture", "Influencias del zodíaco"),
    HammerfestQuest::new_unchecked(2, "Premiers pas", "First steps", "Primeros pasos"),
    HammerfestQuest::new_unchecked(3, "L'aventure commence", "The adventure begins", "La aventura comienza"),
    HammerfestQuest::new_unchecked(4, "Une destinée épique", "An epic fate", "Un destino épico"),
    HammerfestQuest::new_unchecked(5, "Persévérance", "Perseverance", "Perseverancia"),
    HammerfestQuest::new_unchecked(6, "Gourmandise", "Delicacies", "Gourmand"),
    HammerfestQuest::new_unchecked(7, "Du sucre !", "Some sugar!", "¡Quiero algo dulce!"),
    HammerfestQuest::new_unchecked(8, "Malnutrition", "Malnutrition", "Malnutrición"),
    HammerfestQuest::new_unchecked(9, "Goût raffiné", "Good taste", "Gusto refinado"),
    HammerfestQuest::new_unchecked(10, "Avancée technologique", "Technological advance", "Avance tecnológico"),
    HammerfestQuest::new_unchecked(11, "Le petit guide des Champignons", "Small guide to mushrooms", "La pequeña guía de hongos"),
    HammerfestQuest::new_unchecked(12, "Trouver les pièces d'or secrètes !", "Find the secret golden coins!", "¡Encuentra las monedas de oro secretas!"),
    HammerfestQuest::new_unchecked(13, "Le grimoire des Etoiles", "The book of Magic Stars", "El grimorio de las Estrellas"),
    HammerfestQuest::new_unchecked(14, "Armageddon", "Armageddon", "Armageddon"),
    HammerfestQuest::new_unchecked(15, "Régime MotionTwin", "MotionTwin Diet", "Régimen MotionTwin"),
    HammerfestQuest::new_unchecked(16, "Créateur de jeu en devenir", "Creator of games", "Creador de juegos innovadores"),
    HammerfestQuest::new_unchecked(17, "La vie est une boîte de chocolats", "Life is like a box of chocolates...", "La vida es como una caja de bombones..."),
    HammerfestQuest::new_unchecked(18, "Le trésor Oune-difaïned", "Difaïned treasure", "El tesoro difaïned"),
    HammerfestQuest::new_unchecked(19, "Super size me !", "Super size me!", "Super size me!"),
    HammerfestQuest::new_unchecked(20, "Maître joaillier", "Master jeweller", "Maestro joyero"),
    HammerfestQuest::new_unchecked(21, "Grand prédateur", "Great Predator", "Gran Depredador"),
    HammerfestQuest::new_unchecked(22, "Expert en salades et potages", "Expert in salads and stews", "Experto en ensaladas y potajes"),
    HammerfestQuest::new_unchecked(23, "Festin d'Hammerfest", "Hammerfest Feast", "Festín de Hammerfest"),
    HammerfestQuest::new_unchecked(24, "Goûter d'anniversaire", "Birthday party", "Merienda de cumpleaños"),
    HammerfestQuest::new_unchecked(25, "Bon vivant", "Bon vivant", "Vividor"),
    HammerfestQuest::new_unchecked(26, "Fondue norvégienne", "Norwegian fondue", "Fondue noruega"),
    HammerfestQuest::new_unchecked(27, "Mystère de Guu", "Guu's mistery", "Misterio de Guu"),
    HammerfestQuest::new_unchecked(28, "Friandises divines", "Divine sweets", "Chucherías divinas"),
    HammerfestQuest::new_unchecked(29, "Igor et Cortex", "Igor and Cortex", "Igor y Cortex"),
    HammerfestQuest::new_unchecked(30, "Affronter l'obscurité", "Facing the darkness", "Afrontar la oscuridad"),
    HammerfestQuest::new_unchecked(31, "Et la lumière fût !", "And light appeared!", "¡Y se hizo la luz!"),
    HammerfestQuest::new_unchecked(32, "Noël sur Hammerfest !", "Christmas in Hammerfest!", "¡Navidad en Hammerfest!"),
    HammerfestQuest::new_unchecked(33, "Joyeux anniversaire Igor", "Happy birthday Igor", "Feliz cumpleaños Igor"),
    HammerfestQuest::new_unchecked(34, "Cadeau céleste", "Celestial present", "Regalo celestial"),
    HammerfestQuest::new_unchecked(35, "Achat de parties amélioré", "Game purchase enhanced", "Compra de partidas mejorada"),
    HammerfestQuest::new_unchecked(36, "Exterminateur de Sorbex", "Sorbex exterminator", "Exterminador de Sorbetex"),
    HammerfestQuest::new_unchecked(37, "Désamorceur de Bombinos", "Bombino disposal expert", "Desactivador de Bombinos"),
    HammerfestQuest::new_unchecked(38, "Tueur de poires", "Pear killer", "Asesino de peras"),
    HammerfestQuest::new_unchecked(39, "Mixeur de Tagadas", "Tagadas mixer", "Triturador de Tagadas"),
    HammerfestQuest::new_unchecked(40, "Kiwi frotte s'y pique", "Kiwi itches! ouch, it scratches!", "Kiwi rasca, vaya cómo pica..."),
    HammerfestQuest::new_unchecked(41, "Chasseur de Bondissantes", "Leaping Hunter", "Cazador de Sandinas"),
    HammerfestQuest::new_unchecked(42, "Tronçonneur d'Ananargeddons", "Armaggedon-Pineapple Killer", "Aniquilador de Piñaguedones"),
    HammerfestQuest::new_unchecked(43, "Roi de Hammerfest", "Hammerfest King", "Rey de Hammerfest"),
    HammerfestQuest::new_unchecked(44, "Chapelier fou", "Mad hatter", "Sombrero loco"),
    HammerfestQuest::new_unchecked(45, "Poney éco-terroriste", "Eco-terrorist pony", "Poni eco-terrorista"),
    HammerfestQuest::new_unchecked(46, "Le Pioupiouz est en toi", "The Pioupiou is in you", "El Pioupiouz está en ti"),
    HammerfestQuest::new_unchecked(47, "Chasseur de champignons", "Mushrooms hunter", "Cazador de champiñones"),
    HammerfestQuest::new_unchecked(48, "Successeur de Tuberculoz", "Tuber's successor", "Sucesor de Tubérculo"),
    HammerfestQuest::new_unchecked(49, "La première clé !", "The first Key!", "¡La primera Llave!"),
    HammerfestQuest::new_unchecked(50, "Rigor Dangerous", "Rigor Dangerous", "Rigor Dangerous"),
    HammerfestQuest::new_unchecked(51, "La Méluzzine perdue", "The lost Meluzin", "La Meluzine perdida"),
    HammerfestQuest::new_unchecked(52, "Enfin le Bourru !", "At last, the drunk man!", "¡Por fin el borracho!"),
    HammerfestQuest::new_unchecked(53, "Congélation", "Frozen", "Congelación"),
    HammerfestQuest::new_unchecked(54, "Une clé rouillée", "A rusty key", "Una llave herrumbrosa"),
    HammerfestQuest::new_unchecked(55, "Laissez passer !", "Let it go!", "¡Dejadlo libre!"),
    HammerfestQuest::new_unchecked(56, "Les mondes ardus", "The Arduous Worlds", "Los Mundos Arduos"),
    HammerfestQuest::new_unchecked(57, "Viiiite !", "Quickly!", "¡Ráaapido!"),
    HammerfestQuest::new_unchecked(58, "Faire les poches à Tubz", "Empty Tuber's pocket", "Vacíarle los bolsillos a Tubérculo"),
    HammerfestQuest::new_unchecked(59, "Tuberculoz, seigneur des enfers", "Tuber, Master of Hell", "Tubérculo, señor de los infiernos"),
    HammerfestQuest::new_unchecked(60, "L'eau ferrigineuneuse", "Metallic water", "El agua que sabe a perfume"),
    HammerfestQuest::new_unchecked(61, "Paperasse administrative", "Paperwork", "Papeleo"),
    HammerfestQuest::new_unchecked(62, "Meilleur joueur", "Best Player", "Mejor jugador"),
    HammerfestQuest::new_unchecked(63, "Miroir, mon beau miroir", "Mirror, my beautiful mirror", "Espejo, mi bonito espejo"),
    HammerfestQuest::new_unchecked(64, "Mode cauchemar", "Nightmare mode", "Modo pesadilla"),
    HammerfestQuest::new_unchecked(65, "L'aventure continue !", "The adventure continues!", "¡La aventura continúa!"),
    HammerfestQuest::new_unchecked(66, "Joyau d'Ankhel", "Ankhel Jewel", "Joya de Ankhel"),
    HammerfestQuest::new_unchecked(67, "Sandy commence l'aventure !", "Sandy's adventure begins!", "¡Sandy comienza la aventura!"),
    HammerfestQuest::new_unchecked(68, "Miroir, NOTRE beau miroir", "Mirror, OUR beautiful mirror", "Espejo, NUESTRO bonito espejo"),
    HammerfestQuest::new_unchecked(69, "Mode double cauchemar", "Double-nightmare option", "Modo Doble Pesadilla"),
    HammerfestQuest::new_unchecked(70, "Une grande Amitié", "A great Friendship", "Una gran Amistad"),
    HammerfestQuest::new_unchecked(71, "Apprentissage des canifs volants", "Learning how to launch Shurikens", "Aprendizaje de lanzamiento shurikens"),
    HammerfestQuest::new_unchecked(72, "Shinobi do !", "Shinobi do!", "¡Shinobi do!"),
    HammerfestQuest::new_unchecked(73, "Rapide comme l'éclair !", "As quick as the lightning!", "Rápido como el rayo..."),
    HammerfestQuest::new_unchecked(74, "Maître des Bombes", "Bomb Master", "Maestro de Bombas"),
    HammerfestQuest::new_unchecked(75, "Tombeau de Tuberculoz", "Tuber's tomb", "Tumba de Tubérculo"),
  ]
};

pub struct HammerfestItem {
  pub id: HammerfestItemId,
  pub is_hidden: bool,
}

impl HammerfestItem {
  const unsafe fn new_unchecked(id: u16) -> Self {
    let is_hidden = matches!(id, 1186 | 1187 | 1188 | 1189);
    Self {
      id: HammerfestItemId::new_unchecked(id),
      is_hidden,
    }
  }
}

#[rustfmt::skip]
pub const ITEMS: [HammerfestItem; 357] = unsafe {
  [
    HammerfestItem::new_unchecked(1000),
    HammerfestItem::new_unchecked(1003),
    HammerfestItem::new_unchecked(1008),
    HammerfestItem::new_unchecked(1013),
    HammerfestItem::new_unchecked(1017),
    HammerfestItem::new_unchecked(1027),
    HammerfestItem::new_unchecked(1041),
    HammerfestItem::new_unchecked(1043),
    HammerfestItem::new_unchecked(1047),
    HammerfestItem::new_unchecked(1048),
    HammerfestItem::new_unchecked(1049),
    HammerfestItem::new_unchecked(1050),
    HammerfestItem::new_unchecked(1051),
    HammerfestItem::new_unchecked(1169),
    HammerfestItem::new_unchecked(1185),
    HammerfestItem::new_unchecked(1022),
    HammerfestItem::new_unchecked(1024),
    HammerfestItem::new_unchecked(1025),
    HammerfestItem::new_unchecked(1026),
    HammerfestItem::new_unchecked(1028),
    HammerfestItem::new_unchecked(1040),
    HammerfestItem::new_unchecked(1069),
    HammerfestItem::new_unchecked(1070),
    HammerfestItem::new_unchecked(1071),
    HammerfestItem::new_unchecked(1073),
    HammerfestItem::new_unchecked(1074),
    HammerfestItem::new_unchecked(1075),
    HammerfestItem::new_unchecked(1077),
    HammerfestItem::new_unchecked(1078),
    HammerfestItem::new_unchecked(1079),
    HammerfestItem::new_unchecked(1080),
    HammerfestItem::new_unchecked(1081),
    HammerfestItem::new_unchecked(1082),
    HammerfestItem::new_unchecked(1002),
    HammerfestItem::new_unchecked(1004),
    HammerfestItem::new_unchecked(1005),
    HammerfestItem::new_unchecked(1006),
    HammerfestItem::new_unchecked(1007),
    HammerfestItem::new_unchecked(1012),
    HammerfestItem::new_unchecked(1014),
    HammerfestItem::new_unchecked(1015),
    HammerfestItem::new_unchecked(1016),
    HammerfestItem::new_unchecked(1018),
    HammerfestItem::new_unchecked(1019),
    HammerfestItem::new_unchecked(1023),
    HammerfestItem::new_unchecked(1045),
    HammerfestItem::new_unchecked(1046),
    HammerfestItem::new_unchecked(1009),
    HammerfestItem::new_unchecked(1010),
    HammerfestItem::new_unchecked(1011),
    HammerfestItem::new_unchecked(1001),
    HammerfestItem::new_unchecked(1021),
    HammerfestItem::new_unchecked(1042),
    HammerfestItem::new_unchecked(1055),
    HammerfestItem::new_unchecked(1056),
    HammerfestItem::new_unchecked(1057),
    HammerfestItem::new_unchecked(1142),
    HammerfestItem::new_unchecked(1149),
    HammerfestItem::new_unchecked(1166),
    HammerfestItem::new_unchecked(1020),
    HammerfestItem::new_unchecked(1039),
    HammerfestItem::new_unchecked(1044),
    HammerfestItem::new_unchecked(1060),
    HammerfestItem::new_unchecked(1061),
    HammerfestItem::new_unchecked(1062),
    HammerfestItem::new_unchecked(1076),
    HammerfestItem::new_unchecked(1161),
    HammerfestItem::new_unchecked(1162),
    HammerfestItem::new_unchecked(1163),
    HammerfestItem::new_unchecked(1167),
    HammerfestItem::new_unchecked(1029),
    HammerfestItem::new_unchecked(1030),
    HammerfestItem::new_unchecked(1031),
    HammerfestItem::new_unchecked(1032),
    HammerfestItem::new_unchecked(1033),
    HammerfestItem::new_unchecked(1034),
    HammerfestItem::new_unchecked(1035),
    HammerfestItem::new_unchecked(1036),
    HammerfestItem::new_unchecked(1037),
    HammerfestItem::new_unchecked(1038),
    HammerfestItem::new_unchecked(1164),
    HammerfestItem::new_unchecked(1052),
    HammerfestItem::new_unchecked(1053),
    HammerfestItem::new_unchecked(1054),
    HammerfestItem::new_unchecked(1091),
    HammerfestItem::new_unchecked(1092),
    HammerfestItem::new_unchecked(1093),
    HammerfestItem::new_unchecked(1094),
    HammerfestItem::new_unchecked(1095),
    HammerfestItem::new_unchecked(1096),
    HammerfestItem::new_unchecked(1097),
    HammerfestItem::new_unchecked(1098),
    HammerfestItem::new_unchecked(1099),
    HammerfestItem::new_unchecked(1063),
    HammerfestItem::new_unchecked(1064),
    HammerfestItem::new_unchecked(1065),
    HammerfestItem::new_unchecked(1066),
    HammerfestItem::new_unchecked(1067),
    HammerfestItem::new_unchecked(1068),
    HammerfestItem::new_unchecked(1083),
    HammerfestItem::new_unchecked(1084),
    HammerfestItem::new_unchecked(1085),
    HammerfestItem::new_unchecked(1086),
    HammerfestItem::new_unchecked(1087),
    HammerfestItem::new_unchecked(1088),
    HammerfestItem::new_unchecked(1089),
    HammerfestItem::new_unchecked(1090),
    HammerfestItem::new_unchecked(1106),
    HammerfestItem::new_unchecked(1107),
    HammerfestItem::new_unchecked(1108),
    HammerfestItem::new_unchecked(1109),
    HammerfestItem::new_unchecked(1110),
    HammerfestItem::new_unchecked(1111),
    HammerfestItem::new_unchecked(1100),
    HammerfestItem::new_unchecked(1101),
    HammerfestItem::new_unchecked(1102),
    HammerfestItem::new_unchecked(1103),
    HammerfestItem::new_unchecked(1104),
    HammerfestItem::new_unchecked(1105),
    HammerfestItem::new_unchecked(1168),
    HammerfestItem::new_unchecked(1112),
    HammerfestItem::new_unchecked(1113),
    HammerfestItem::new_unchecked(1114),
    HammerfestItem::new_unchecked(1115),
    HammerfestItem::new_unchecked(1116),
    HammerfestItem::new_unchecked(1117),
    HammerfestItem::new_unchecked(1118),
    HammerfestItem::new_unchecked(1119),
    HammerfestItem::new_unchecked(1120),
    HammerfestItem::new_unchecked(1121),
    HammerfestItem::new_unchecked(1122),
    HammerfestItem::new_unchecked(1123),
    HammerfestItem::new_unchecked(1124),
    HammerfestItem::new_unchecked(1125),
    HammerfestItem::new_unchecked(1126),
    HammerfestItem::new_unchecked(1127),
    HammerfestItem::new_unchecked(1128),
    HammerfestItem::new_unchecked(1129),
    HammerfestItem::new_unchecked(1130),
    HammerfestItem::new_unchecked(1131),
    HammerfestItem::new_unchecked(1132),
    HammerfestItem::new_unchecked(1133),
    HammerfestItem::new_unchecked(1134),
    HammerfestItem::new_unchecked(1135),
    HammerfestItem::new_unchecked(1136),
    HammerfestItem::new_unchecked(1141),
    HammerfestItem::new_unchecked(1143),
    HammerfestItem::new_unchecked(1137),
    HammerfestItem::new_unchecked(1138),
    HammerfestItem::new_unchecked(1139),
    HammerfestItem::new_unchecked(1140),
    HammerfestItem::new_unchecked(1144),
    HammerfestItem::new_unchecked(1145),
    HammerfestItem::new_unchecked(1146),
    HammerfestItem::new_unchecked(1147),
    HammerfestItem::new_unchecked(1148),
    HammerfestItem::new_unchecked(1150),
    HammerfestItem::new_unchecked(1151),
    HammerfestItem::new_unchecked(1152),
    HammerfestItem::new_unchecked(1153),
    HammerfestItem::new_unchecked(1154),
    HammerfestItem::new_unchecked(1155),
    HammerfestItem::new_unchecked(1159),
    HammerfestItem::new_unchecked(1160),
    HammerfestItem::new_unchecked(1058),
    HammerfestItem::new_unchecked(1059),
    HammerfestItem::new_unchecked(1072),
    HammerfestItem::new_unchecked(1156),
    HammerfestItem::new_unchecked(1157),
    HammerfestItem::new_unchecked(1158),
    HammerfestItem::new_unchecked(1165),
    HammerfestItem::new_unchecked(1170),
    HammerfestItem::new_unchecked(1171),
    HammerfestItem::new_unchecked(1172),
    HammerfestItem::new_unchecked(1173),
    HammerfestItem::new_unchecked(1174),
    HammerfestItem::new_unchecked(1175),
    HammerfestItem::new_unchecked(1176),
    HammerfestItem::new_unchecked(1177),
    HammerfestItem::new_unchecked(1178),
    HammerfestItem::new_unchecked(1179),
    HammerfestItem::new_unchecked(1180),
    HammerfestItem::new_unchecked(1181),
    HammerfestItem::new_unchecked(1182),
    HammerfestItem::new_unchecked(1183),
    HammerfestItem::new_unchecked(1184),
    HammerfestItem::new_unchecked(1190),
    HammerfestItem::new_unchecked(1191),
    HammerfestItem::new_unchecked(1194),
    HammerfestItem::new_unchecked(1197),
    HammerfestItem::new_unchecked(1198),
    HammerfestItem::new_unchecked(1199),
    HammerfestItem::new_unchecked(1200),
    HammerfestItem::new_unchecked(1193),
    HammerfestItem::new_unchecked(1196),
    HammerfestItem::new_unchecked(1192),
    HammerfestItem::new_unchecked(1195),
    HammerfestItem::new_unchecked(1201),
    HammerfestItem::new_unchecked(1202),
    HammerfestItem::new_unchecked(1203),
    HammerfestItem::new_unchecked(1204),
    HammerfestItem::new_unchecked(1205),
    HammerfestItem::new_unchecked(1206),
    HammerfestItem::new_unchecked(1207),
    HammerfestItem::new_unchecked(1208),
    HammerfestItem::new_unchecked(1209),
    HammerfestItem::new_unchecked(1210),
    HammerfestItem::new_unchecked(1211),
    HammerfestItem::new_unchecked(1212),
    HammerfestItem::new_unchecked(1213),
    HammerfestItem::new_unchecked(1214),
    HammerfestItem::new_unchecked(1215),
    HammerfestItem::new_unchecked(1216),
    HammerfestItem::new_unchecked(1217),
    HammerfestItem::new_unchecked(1218),
    HammerfestItem::new_unchecked(1219),
    HammerfestItem::new_unchecked(1220),
    HammerfestItem::new_unchecked(1225),
    HammerfestItem::new_unchecked(1226),
    HammerfestItem::new_unchecked(1227),
    HammerfestItem::new_unchecked(1237),
    HammerfestItem::new_unchecked(1238),
    HammerfestItem::new_unchecked(1221),
    HammerfestItem::new_unchecked(1222),
    HammerfestItem::new_unchecked(1223),
    HammerfestItem::new_unchecked(1224),
    HammerfestItem::new_unchecked(1228),
    HammerfestItem::new_unchecked(1236),
    HammerfestItem::new_unchecked(1229),
    HammerfestItem::new_unchecked(1230),
    HammerfestItem::new_unchecked(1231),
    HammerfestItem::new_unchecked(1232),
    HammerfestItem::new_unchecked(1233),
    HammerfestItem::new_unchecked(1234),
    HammerfestItem::new_unchecked(1235),
    HammerfestItem::new_unchecked(1186),
    HammerfestItem::new_unchecked(1187),
    HammerfestItem::new_unchecked(1188),
    HammerfestItem::new_unchecked(1189),
    HammerfestItem::new_unchecked(0),
    HammerfestItem::new_unchecked(3),
    HammerfestItem::new_unchecked(4),
    HammerfestItem::new_unchecked(7),
    HammerfestItem::new_unchecked(13),
    HammerfestItem::new_unchecked(21),
    HammerfestItem::new_unchecked(24),
    HammerfestItem::new_unchecked(64),
    HammerfestItem::new_unchecked(74),
    HammerfestItem::new_unchecked(77),
    HammerfestItem::new_unchecked(84),
    HammerfestItem::new_unchecked(102),
    HammerfestItem::new_unchecked(113),
    HammerfestItem::new_unchecked(115),
    HammerfestItem::new_unchecked(116),
    HammerfestItem::new_unchecked(117),
    HammerfestItem::new_unchecked(1),
    HammerfestItem::new_unchecked(5),
    HammerfestItem::new_unchecked(8),
    HammerfestItem::new_unchecked(11),
    HammerfestItem::new_unchecked(18),
    HammerfestItem::new_unchecked(22),
    HammerfestItem::new_unchecked(23),
    HammerfestItem::new_unchecked(25),
    HammerfestItem::new_unchecked(27),
    HammerfestItem::new_unchecked(28),
    HammerfestItem::new_unchecked(38),
    HammerfestItem::new_unchecked(39),
    HammerfestItem::new_unchecked(65),
    HammerfestItem::new_unchecked(66),
    HammerfestItem::new_unchecked(69),
    HammerfestItem::new_unchecked(71),
    HammerfestItem::new_unchecked(82),
    HammerfestItem::new_unchecked(106),
    HammerfestItem::new_unchecked(107),
    HammerfestItem::new_unchecked(2),
    HammerfestItem::new_unchecked(6),
    HammerfestItem::new_unchecked(9),
    HammerfestItem::new_unchecked(12),
    HammerfestItem::new_unchecked(19),
    HammerfestItem::new_unchecked(30),
    HammerfestItem::new_unchecked(31),
    HammerfestItem::new_unchecked(36),
    HammerfestItem::new_unchecked(70),
    HammerfestItem::new_unchecked(72),
    HammerfestItem::new_unchecked(73),
    HammerfestItem::new_unchecked(75),
    HammerfestItem::new_unchecked(76),
    HammerfestItem::new_unchecked(80),
    HammerfestItem::new_unchecked(81),
    HammerfestItem::new_unchecked(86),
    HammerfestItem::new_unchecked(87),
    HammerfestItem::new_unchecked(88),
    HammerfestItem::new_unchecked(89),
    HammerfestItem::new_unchecked(90),
    HammerfestItem::new_unchecked(93),
    HammerfestItem::new_unchecked(95),
    HammerfestItem::new_unchecked(96),
    HammerfestItem::new_unchecked(99),
    HammerfestItem::new_unchecked(101),
    HammerfestItem::new_unchecked(112),
    HammerfestItem::new_unchecked(14),
    HammerfestItem::new_unchecked(15),
    HammerfestItem::new_unchecked(16),
    HammerfestItem::new_unchecked(17),
    HammerfestItem::new_unchecked(32),
    HammerfestItem::new_unchecked(33),
    HammerfestItem::new_unchecked(34),
    HammerfestItem::new_unchecked(35),
    HammerfestItem::new_unchecked(40),
    HammerfestItem::new_unchecked(41),
    HammerfestItem::new_unchecked(42),
    HammerfestItem::new_unchecked(43),
    HammerfestItem::new_unchecked(44),
    HammerfestItem::new_unchecked(45),
    HammerfestItem::new_unchecked(46),
    HammerfestItem::new_unchecked(47),
    HammerfestItem::new_unchecked(48),
    HammerfestItem::new_unchecked(49),
    HammerfestItem::new_unchecked(50),
    HammerfestItem::new_unchecked(51),
    HammerfestItem::new_unchecked(52),
    HammerfestItem::new_unchecked(53),
    HammerfestItem::new_unchecked(54),
    HammerfestItem::new_unchecked(55),
    HammerfestItem::new_unchecked(56),
    HammerfestItem::new_unchecked(57),
    HammerfestItem::new_unchecked(58),
    HammerfestItem::new_unchecked(59),
    HammerfestItem::new_unchecked(60),
    HammerfestItem::new_unchecked(61),
    HammerfestItem::new_unchecked(62),
    HammerfestItem::new_unchecked(63),
    HammerfestItem::new_unchecked(103),
    HammerfestItem::new_unchecked(104),
    HammerfestItem::new_unchecked(105),
    HammerfestItem::new_unchecked(20),
    HammerfestItem::new_unchecked(78),
    HammerfestItem::new_unchecked(79),
    HammerfestItem::new_unchecked(91),
    HammerfestItem::new_unchecked(94),
    HammerfestItem::new_unchecked(83),
    HammerfestItem::new_unchecked(97),
    HammerfestItem::new_unchecked(98),
    HammerfestItem::new_unchecked(100),
    HammerfestItem::new_unchecked(108),
    HammerfestItem::new_unchecked(29),
    HammerfestItem::new_unchecked(37),
    HammerfestItem::new_unchecked(67),
    HammerfestItem::new_unchecked(85),
    HammerfestItem::new_unchecked(92),
    HammerfestItem::new_unchecked(68),
    HammerfestItem::new_unchecked(26),
    HammerfestItem::new_unchecked(109),
    HammerfestItem::new_unchecked(110),
    HammerfestItem::new_unchecked(111),
    HammerfestItem::new_unchecked(10),
    HammerfestItem::new_unchecked(114),
  ]
};

pub static ITEMS_BY_ID: Lazy<HashMap<HammerfestItemId, &'static HammerfestItem>> = Lazy::new(|| {
  let mut map: HashMap<HammerfestItemId, &'static HammerfestItem> = HashMap::new();
  for item in ITEMS.iter() {
    map.insert(item.id, item);
  }
  map
});
