import { HammerfestQuestId } from "@eternal-twin/core/lib/hammerfest/hammerfest-quest-id.js";
import { HammerfestQuestName } from "@eternal-twin/core/lib/hammerfest/hammerfest-quest-name.js";
import { HammerfestServer } from "@eternal-twin/core/lib/hammerfest/hammerfest-server.js";

export const SIGNIN_TO_SERVER: ReadonlyMap<string, HammerfestServer> = new Map([
  ["Login", "hfest.net"],
  ["Entrer", "hammerfest.fr"],
  ["Entrar", "hammerfest.es"],
]);

export const EVNI_HEADER_TO_SERVER: ReadonlyMap<string, HammerfestServer> = new Map([
  ["Oops!", "hfest.net"],
  ["Ooops !", "hammerfest.fr"],
  ["¡Ay!", "hammerfest.es"],
]);

export const QUEST_NAME_TO_QUEST_ID: ReadonlyMap<HammerfestServer, ReadonlyMap<HammerfestQuestName, HammerfestQuestId>> = new Map([
  [
    "hfest.net",
    new Map([
      ["Constellations", "0"],
      ["Zodiac mixture", "1"],
      ["First steps", "2"],
      ["The adventure begins", "3"],
      ["An epic fate", "4"],
      ["Perseverance", "5"],
      ["Delicacies", "6"],
      ["Some sugar!", "7"],
      ["Malnutrition", "8"],
      ["Good taste", "9"],
      ["Technological advance", "10"],
      ["Small guide to mushrooms", "11"],
      ["Find the secret golden coins!", "12"],
      ["The book of Magic Stars", "13"],
      ["Armageddon", "14"],
      ["MotionTwin Diet", "15"],
      ["Creator of games", "16"],
      ["Life is like a box of chocolates...", "17"],
      ["Difaïned treasure", "18"],
      ["Super size me!", "19"],
      ["Master jeweller", "20"],
      ["Great Predator", "21"],
      ["Expert in salads and stews", "22"],
      ["Hammerfest Feast", "23"],
      ["Birthday party", "24"],
      ["Bon vivant", "25"],
      ["Norwegian fondue", "26"],
      ["Guu's mistery", "27"],
      ["Divine sweets", "28"],
      ["Igor and Cortex", "29"],
      ["Facing the darkness", "30"],
      ["And light appeared!", "31"],
      ["Christmas in Hammerfest!", "32"],
      ["Happy birthday Igor", "33"],
      ["Celestial present", "34"],
      ["Game purchase enhanced", "35"],
      ["Sorbex exterminator", "36"],
      ["Bombino disposal expert", "37"],
      ["Pear killer", "38"],
      ["Tagadas mixer", "39"],
      ["Kiwi itches! ouch, it scratches!", "40"],
      ["Leaping Hunter", "41"],
      ["Armaggedon-Pineapple Killer", "42"],
      ["Hammerfest King", "43"],
      ["Mad hatter", "44"],
      ["Eco-terrorist pony", "45"],
      ["The Pioupiou is in you", "46"],
      ["Mushrooms hunter", "47"],
      ["Tuber's successor", "48"],
      ["The first Key!", "49"],
      ["Rigor Dangerous", "50"],
      ["The lost Meluzin", "51"],
      ["At last, the drunk man!", "52"],
      ["Frozen", "53"],
      ["A rusty key", "54"],
      ["Let it go!", "55"],
      ["The Arduous Worlds", "56"],
      ["Quickly!", "57"],
      ["Empty Tuber's pocket", "58"],
      ["Tuber, Master of Hell", "59"],
      ["Metallic water", "60"],
      ["Paperwork", "61"],
      ["Best Player", "62"],
      ["Mirror, my beautiful mirror", "63"],
      ["Nightmare mode", "64"],
      ["The adventure continues!", "65"],
      ["Ankhel Jewel", "66"],
      ["Sandy's adventure begins!", "67"],
      ["Mirror, OUR beautiful mirror", "68"],
      ["Double-nightmare option", "69"],
      ["A great Friendship", "70"],
      ["Learning how to launch Shurikens", "71"],
      ["Shinobi do!", "72"],
      ["As quick as the lightning!", "73"],
      ["Bomb Master", "74"],
      ["Tuber's tomb", "75"],
    ]),
  ],
  [
    "hammerfest.fr",
    new Map([
      ["Les constellations", "0"],
      ["Mixtures du zodiaque", "1"],
      ["Premiers pas", "2"],
      ["L'aventure commence", "3"],
      ["Une destinée épique", "4"],
      ["Persévérance", "5"],
      ["Gourmandise", "6"],
      ["Du sucre !", "7"],
      ["Malnutrition", "8"],
      ["Goût raffiné", "9"],
      ["Avancée technologique", "10"],
      ["Le petit guide des Champignons", "11"],
      ["Trouver les pièces d'or secrètes !", "12"],
      ["Le grimoire des Etoiles", "13"],
      ["Armageddon", "14"],
      ["Régime MotionTwin", "15"],
      ["Créateur de jeu en devenir", "16"],
      ["La vie est une boîte de chocolats", "17"],
      ["Le trésor Oune-difaïned", "18"],
      ["Super size me !", "19"],
      ["Maître joaillier", "20"],
      ["Grand prédateur", "21"],
      ["Expert en salades et potages", "22"],
      ["Festin d'Hammerfest", "23"],
      ["Goûter d'anniversaire", "24"],
      ["Bon vivant", "25"],
      ["Fondue norvégienne", "26"],
      ["Mystère de Guu", "27"],
      ["Friandises divines", "28"],
      ["Igor et Cortex", "29"],
      ["Affronter l'obscurité", "30"],
      ["Et la lumière fût !", "31"],
      ["Noël sur Hammerfest !", "32"],
      ["Joyeux anniversaire Igor", "33"],
      ["Cadeau céleste", "34"],
      ["Achat de parties amélioré", "35"],
      ["Exterminateur de Sorbex", "36"],
      ["Désamorceur de Bombinos", "37"],
      ["Tueur de poires", "38"],
      ["Mixeur de Tagadas", "39"],
      ["Kiwi frotte s'y pique", "40"],
      ["Chasseur de Bondissantes", "41"],
      ["Tronçonneur d'Ananargeddons", "42"],
      ["Roi de Hammerfest", "43"],
      ["Chapelier fou", "44"],
      ["Poney éco-terroriste", "45"],
      ["Le Pioupiouz est en toi", "46"],
      ["Chasseur de champignons", "47"],
      ["Successeur de Tuberculoz", "48"],
      ["La première clé !", "49"],
      ["Rigor Dangerous", "50"],
      ["La Méluzzine perdue", "51"],
      ["Enfin le Bourru !", "52"],
      ["Congélation", "53"],
      ["Une clé rouillée", "54"],
      ["Laissez passer !", "55"],
      ["Les mondes ardus", "56"],
      ["Viiiite !", "57"],
      ["Faire les poches à Tubz", "58"],
      ["Tuberculoz, seigneur des enfers", "59"],
      ["L'eau ferrigineuneuse", "60"],
      ["Paperasse administrative", "61"],
      ["Meilleur joueur", "62"],
      ["Miroir, mon beau miroir", "63"],
      ["Mode cauchemar", "64"],
      ["L'aventure continue !", "65"],
      ["Joyau d'Ankhel", "66"],
      ["Sandy commence l'aventure !", "67"],
      ["Miroir, NOTRE beau miroir", "68"],
      ["Mode double cauchemar", "69"],
      ["Une grande Amitié", "70"],
      ["Apprentissage des canifs volants", "71"],
      ["Shinobi do !", "72"],
      ["Rapide comme l'éclair !", "73"],
      ["Maître des Bombes", "74"],
      ["Tombeau de Tuberculoz", "75"],
    ]),
  ],
  [
    "hammerfest.es",
    new Map([
      ["Las constelaciones", "0"],
      ["Influencias del zodíaco", "1"],
      ["Primeros pasos", "2"],
      ["La aventura comienza", "3"],
      ["Un destino épico", "4"],
      ["Perseverancia", "5"],
      ["Gourmand", "6"],
      ["¡Quiero algo dulce!", "7"],
      ["Malnutrición", "8"],
      ["Gusto refinado", "9"],
      ["Avance tecnológico", "10"],
      ["La pequeña guía de hongos", "11"],
      ["¡Encuentra las monedas de oro secretas!", "12"],
      ["El grimorio de las Estrellas", "13"],
      ["Armageddon", "14"],
      ["Régimen MotionTwin", "15"],
      ["Creador de juegos innovadores", "16"],
      ["La vida es como una caja de bombones...", "17"],
      ["El tesoro difaïned", "18"],
      ["Super size me!", "19"],
      ["Maestro joyero", "20"],
      ["Gran Depredador", "21"],
      ["Experto en ensaladas y potajes", "22"],
      ["Festín de Hammerfest", "23"],
      ["Merienda de cumpleaños", "24"],
      ["Vividor", "25"],
      ["Fondue noruega", "26"],
      ["Misterio de Guu", "27"],
      ["Chucherías divinas", "28"],
      ["Igor y Cortex", "29"],
      ["Afrontar la oscuridad", "30"],
      ["¡Y se hizo la luz!", "31"],
      ["¡Navidad en Hammerfest!", "32"],
      ["Feliz cumpleaños Igor", "33"],
      ["Regalo celestial", "34"],
      ["Compra de partidas mejorada", "35"],
      ["Exterminador de Sorbetex", "36"],
      ["Desactivador de Bombinos", "37"],
      ["Asesino de peras", "38"],
      ["Triturador de Tagadas", "39"],
      ["Kiwi rasca, vaya cómo pica...", "40"],
      ["Cazador de Sandinas", "41"],
      ["Aniquilador de Piñaguedones", "42"],
      ["Rey de Hammerfest", "43"],
      ["Sombrero loco", "44"],
      ["Poni eco-terrorista", "45"],
      ["El Pioupiouz está en ti", "46"],
      ["Cazador de champiñones", "47"],
      ["Sucesor de Tubérculo", "48"],
      ["¡La primera Llave!", "49"],
      ["Rigor Dangerous", "50"],
      ["La Meluzine perdida", "51"],
      ["¡Por fin el borracho!", "52"],
      ["Congelación", "53"],
      ["Una llave herrumbrosa", "54"],
      ["¡Dejadlo libre!", "55"],
      ["Los Mundos Arduos", "56"],
      ["¡Ráaapido!", "57"],
      ["Vacíarle los bolsillos a Tubérculo", "58"],
      ["Tubérculo, señor de los infiernos", "59"],
      ["El agua que sabe a perfume", "60"],
      ["Papeleo", "61"],
      ["Mejor jugador", "62"],
      ["Espejo, mi bonito espejo", "63"],
      ["Modo pesadilla", "64"],
      ["¡La aventura continúa!", "65"],
      ["Joya de Ankhel", "66"],
      ["¡Sandy comienza la aventura!", "67"],
      ["Espejo, NUESTRO bonito espejo", "68"],
      ["Modo Doble Pesadilla", "69"],
      ["Una gran Amistad", "70"],
      ["Aprendizaje de lanzamiento shurikens", "71"],
      ["¡Shinobi do!", "72"],
      ["Rápido como el rayo...", "73"],
      ["Maestro de Bombas", "74"],
      ["Tumba de Tubérculo", "75"],
    ]),
  ],
]);
