use std::collections::HashMap;

use etwin_core::hammerfest::{HammerfestQuestId, HammerfestServer};
use once_cell::sync::Lazy;

pub struct ScraperTexts {
  pub quest_names: HashMap<&'static str, HammerfestQuestId>,
}

impl ScraperTexts {
  pub fn get(server: HammerfestServer) -> &'static Self {
    match server {
      HammerfestServer::HammerfestFr => &TEXTS_FR,
      HammerfestServer::HammerfestEs => &TEXTS_ES,
      HammerfestServer::HfestNet => &TEXTS_EN,
    }
  }

  fn empty() -> Self {
    ScraperTexts {
      quest_names: HashMap::new(),
    }
  }

  fn quest(mut self, name: &'static str, id: &str) -> Self {
    let id = HammerfestQuestId::try_from_string(id.to_owned()).expect("failed to parse quest id");
    self.quest_names.insert(name, id);
    self
  }
}

static TEXTS_FR: Lazy<ScraperTexts> = Lazy::new(|| {
  ScraperTexts::empty()
    .quest("Les constellations", "0")
    .quest("Mixtures du zodiaque", "1")
    .quest("Premiers pas", "2")
    .quest("L'aventure commence", "3")
    .quest("Une destinée épique", "4")
    .quest("Persévérance", "5")
    .quest("Gourmandise", "6")
    .quest("Du sucre !", "7")
    .quest("Malnutrition", "8")
    .quest("Goût raffiné", "9")
    .quest("Avancée technologique", "10")
    .quest("Le petit guide des Champignons", "11")
    .quest("Trouver les pièces d'or secrètes !", "12")
    .quest("Le grimoire des Etoiles", "13")
    .quest("Armageddon", "14")
    .quest("Régime MotionTwin", "15")
    .quest("Créateur de jeu en devenir", "16")
    .quest("La vie est une boîte de chocolats", "17")
    .quest("Le trésor Oune-difaïned", "18")
    .quest("Super size me !", "19")
    .quest("Maître joaillier", "20")
    .quest("Grand prédateur", "21")
    .quest("Expert en salades et potages", "22")
    .quest("Festin d'Hammerfest", "23")
    .quest("Goûter d'anniversaire", "24")
    .quest("Bon vivant", "25")
    .quest("Fondue norvégienne", "26")
    .quest("Mystère de Guu", "27")
    .quest("Friandises divines", "28")
    .quest("Igor et Cortex", "29")
    .quest("Affronter l'obscurité", "30")
    .quest("Et la lumière fût !", "31")
    .quest("Noël sur Hammerfest !", "32")
    .quest("Joyeux anniversaire Igor", "33")
    .quest("Cadeau céleste", "34")
    .quest("Achat de parties amélioré", "35")
    .quest("Exterminateur de Sorbex", "36")
    .quest("Désamorceur de Bombinos", "37")
    .quest("Tueur de poires", "38")
    .quest("Mixeur de Tagadas", "39")
    .quest("Kiwi frotte s'y pique", "40")
    .quest("Chasseur de Bondissantes", "41")
    .quest("Tronçonneur d'Ananargeddons", "42")
    .quest("Roi de Hammerfest", "43")
    .quest("Chapelier fou", "44")
    .quest("Poney éco-terroriste", "45")
    .quest("Le Pioupiouz est en toi", "46")
    .quest("Chasseur de champignons", "47")
    .quest("Successeur de Tuberculoz", "48")
    .quest("La première clé !", "49")
    .quest("Rigor Dangerous", "50")
    .quest("La Méluzzine perdue", "51")
    .quest("Enfin le Bourru !", "52")
    .quest("Congélation", "53")
    .quest("Une clé rouillée", "54")
    .quest("Laissez passer !", "55")
    .quest("Les mondes ardus", "56")
    .quest("Viiiite !", "57")
    .quest("Faire les poches à Tubz", "58")
    .quest("Tuberculoz, seigneur des enfers", "59")
    .quest("L'eau ferrigineuneuse", "60")
    .quest("Paperasse administrative", "61")
    .quest("Meilleur joueur", "62")
    .quest("Miroir, mon beau miroir", "63")
    .quest("Mode cauchemar", "64")
    .quest("L'aventure continue !", "65")
    .quest("Joyau d'Ankhel", "66")
    .quest("Sandy commence l'aventure !", "67")
    .quest("Miroir, NOTRE beau miroir", "68")
    .quest("Mode double cauchemar", "69")
    .quest("Une grande Amitié", "70")
    .quest("Apprentissage des canifs volants", "71")
    .quest("Shinobi do !", "72")
    .quest("Rapide comme l'éclair !", "73")
    .quest("Maître des Bombes", "74")
    .quest("Tombeau de Tuberculoz", "75")
});

static TEXTS_ES: Lazy<ScraperTexts> = Lazy::new(|| {
  ScraperTexts::empty()
    .quest("Las constelaciones", "0")
    .quest("Influencias del zodíaco", "1")
    .quest("Primeros pasos", "2")
    .quest("La aventura comienza", "3")
    .quest("Un destino épico", "4")
    .quest("Perseverancia", "5")
    .quest("Gourmand", "6")
    .quest("¡Quiero algo dulce!", "7")
    .quest("Malnutrición", "8")
    .quest("Gusto refinado", "9")
    .quest("Avance tecnológico", "10")
    .quest("La pequeña guía de hongos", "11")
    .quest("¡Encuentra las monedas de oro secretas!", "12")
    .quest("El grimorio de las Estrellas", "13")
    .quest("Armageddon", "14")
    .quest("Régimen MotionTwin", "15")
    .quest("Creador de juegos innovadores", "16")
    .quest("La vida es como una caja de bombones...", "17")
    .quest("El tesoro difaïned", "18")
    .quest("Super size me!", "19")
    .quest("Maestro joyero", "20")
    .quest("Gran Depredador", "21")
    .quest("Experto en ensaladas y potajes", "22")
    .quest("Festín de Hammerfest", "23")
    .quest("Merienda de cumpleaños", "24")
    .quest("Vividor", "25")
    .quest("Fondue noruega", "26")
    .quest("Misterio de Guu", "27")
    .quest("Chucherías divinas", "28")
    .quest("Igor y Cortex", "29")
    .quest("Afrontar la oscuridad", "30")
    .quest("¡Y se hizo la luz!", "31")
    .quest("¡Navidad en Hammerfest!", "32")
    .quest("Feliz cumpleaños Igor", "33")
    .quest("Regalo celestial", "34")
    .quest("Compra de partidas mejorada", "35")
    .quest("Exterminador de Sorbetex", "36")
    .quest("Desactivador de Bombinos", "37")
    .quest("Asesino de peras", "38")
    .quest("Triturador de Tagadas", "39")
    .quest("Kiwi rasca, vaya cómo pica...", "40")
    .quest("Cazador de Sandinas", "41")
    .quest("Aniquilador de Piñaguedones", "42")
    .quest("Rey de Hammerfest", "43")
    .quest("Sombrero loco", "44")
    .quest("Poni eco-terrorista", "45")
    .quest("El Pioupiouz está en ti", "46")
    .quest("Cazador de champiñones", "47")
    .quest("Sucesor de Tubérculo", "48")
    .quest("¡La primera Llave!", "49")
    .quest("Rigor Dangerous", "50")
    .quest("La Meluzine perdida", "51")
    .quest("¡Por fin el borracho!", "52")
    .quest("Congelación", "53")
    .quest("Una llave herrumbrosa", "54")
    .quest("¡Dejadlo libre!", "55")
    .quest("Los Mundos Arduos", "56")
    .quest("¡Ráaapido!", "57")
    .quest("Vacíarle los bolsillos a Tubérculo", "58")
    .quest("Tubérculo, señor de los infiernos", "59")
    .quest("El agua que sabe a perfume", "60")
    .quest("Papeleo", "61")
    .quest("Mejor jugador", "62")
    .quest("Espejo, mi bonito espejo", "63")
    .quest("Modo pesadilla", "64")
    .quest("¡La aventura continúa!", "65")
    .quest("Joya de Ankhel", "66")
    .quest("¡Sandy comienza la aventura!", "67")
    .quest("Espejo, NUESTRO bonito espejo", "68")
    .quest("Modo Doble Pesadilla", "69")
    .quest("Una gran Amistad", "70")
    .quest("Aprendizaje de lanzamiento shurikens", "71")
    .quest("¡Shinobi do!", "72")
    .quest("Rápido como el rayo...", "73")
    .quest("Maestro de Bombas", "74")
    .quest("Tumba de Tubérculo", "75")
});

static TEXTS_EN: Lazy<ScraperTexts> = Lazy::new(|| {
  ScraperTexts::empty()
    .quest("Constellations", "0")
    .quest("Zodiac mixture", "1")
    .quest("First steps", "2")
    .quest("The adventure begins", "3")
    .quest("An epic fate", "4")
    .quest("Perseverance", "5")
    .quest("Delicacies", "6")
    .quest("Some sugar!", "7")
    .quest("Malnutrition", "8")
    .quest("Good taste", "9")
    .quest("Technological advance", "10")
    .quest("Small guide to mushrooms", "11")
    .quest("Find the secret golden coins!", "12")
    .quest("The book of Magic Stars", "13")
    .quest("Armageddon", "14")
    .quest("MotionTwin Diet", "15")
    .quest("Creator of games", "16")
    .quest("Life is like a box of chocolates...", "17")
    .quest("Difaïned treasure", "18")
    .quest("Super size me!", "19")
    .quest("Master jeweller", "20")
    .quest("Great Predator", "21")
    .quest("Expert in salads and stews", "22")
    .quest("Hammerfest Feast", "23")
    .quest("Birthday party", "24")
    .quest("Bon vivant", "25")
    .quest("Norwegian fondue", "26")
    .quest("Guu's mistery", "27")
    .quest("Divine sweets", "28")
    .quest("Igor and Cortex", "29")
    .quest("Facing the darkness", "30")
    .quest("And light appeared!", "31")
    .quest("Christmas in Hammerfest!", "32")
    .quest("Happy birthday Igor", "33")
    .quest("Celestial present", "34")
    .quest("Game purchase enhanced", "35")
    .quest("Sorbex exterminator", "36")
    .quest("Bombino disposal expert", "37")
    .quest("Pear killer", "38")
    .quest("Tagadas mixer", "39")
    .quest("Kiwi itches! ouch, it scratches!", "40")
    .quest("Leaping Hunter", "41")
    .quest("Armaggedon-Pineapple Killer", "42")
    .quest("Hammerfest King", "43")
    .quest("Mad hatter", "44")
    .quest("Eco-terrorist pony", "45")
    .quest("The Pioupiou is in you", "46")
    .quest("Mushrooms hunter", "47")
    .quest("Tuber's successor", "48")
    .quest("The first Key!", "49")
    .quest("Rigor Dangerous", "50")
    .quest("The lost Meluzin", "51")
    .quest("At last, the drunk man!", "52")
    .quest("Frozen", "53")
    .quest("A rusty key", "54")
    .quest("Let it go!", "55")
    .quest("The Arduous Worlds", "56")
    .quest("Quickly!", "57")
    .quest("Empty Tuber's pocket", "58")
    .quest("Tuber, Master of Hell", "59")
    .quest("Metallic water", "60")
    .quest("Paperwork", "61")
    .quest("Best Player", "62")
    .quest("Mirror, my beautiful mirror", "63")
    .quest("Nightmare mode", "64")
    .quest("The adventure continues!", "65")
    .quest("Ankhel Jewel", "66")
    .quest("Sandy's adventure begins!", "67")
    .quest("Mirror, OUR beautiful mirror", "68")
    .quest("Double-nightmare option", "69")
    .quest("A great Friendship", "70")
    .quest("Learning how to launch Shurikens", "71")
    .quest("Shinobi do!", "72")
    .quest("As quick as the lightning!", "73")
    .quest("Bomb Master", "74")
    .quest("Tuber's tomb", "75")
});
