[package]
name = "etwin_services"
version = "0.9.1"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Top-level Eternal-Twin services"
documentation = "https://github.com/eternal-twin/etwin"
homepage = "https://github.com/eternal-twin/etwin"
repository = "https://github.com/eternal-twin/etwin"
readme = "./README.md"
keywords = ["etwin"]
license = "AGPL-3.0-or-later"
edition = "2018"

[dependencies]
jsonwebtoken = "7.2.0"
chrono = "0.4.19"
etwin_core = "0.9.1"
neon = { version = "0.9.1", optional = true, default-features = false, features = ["napi-6"] }
serde = { version = "1.0.130", features = ["derive"] }
thiserror = "1.0.29"
url = { version = "2.2.2", features = ["serde"] }

[dev-dependencies]
etwin_auth_store = "0.9.1"
etwin_config = "0.9.1"
etwin_db_schema = "0.9.1"
etwin_dinoparc_client = "0.9.1"
etwin_dinoparc_store = "0.9.1"
etwin_email_formatter = "0.9.1"
etwin_forum_store = "0.9.1"
etwin_hammerfest_client = "0.9.1"
etwin_hammerfest_store = "0.9.1"
etwin_link_store = "0.9.1"
etwin_mailer = "0.9.1"
etwin_oauth_provider_store = "0.9.1"
etwin_password = { version = "0.9.1", features = ["neon"] }
etwin_twinoid_client = "0.9.1"
etwin_twinoid_store = "0.9.1"
etwin_user_store = "0.9.1"
serde_json = "1.0.67"
serial_test = "0.5.1"
sqlx = { version = "0.5.7", default-features = false, features = ["macros", "chrono", "offline", "postgres", "runtime-tokio-rustls", "uuid"] }
tokio = { version = "1.11.0", features = ["macros", "rt"] }
