// WARNING: DO NOT EDIT THE FILE MANUALLY!
// This file was auto-generated by `cargo xtask kotlin` from the definitions in `xtask/src/metagen/etwin.rs`.

package net.eternaltwin.user

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

@Serializable(with = UserDisplayName.Serializer::class)
data class UserDisplayName(
  val inner: String,
) {
  fun toDebugString(): String = "UserDisplayName(${this})"

  override fun toString(): String = this.inner

  object Serializer : KSerializer<UserDisplayName> {
    override val descriptor: SerialDescriptor =
      PrimitiveSerialDescriptor("net.eternaltwin.user.UserDisplayName", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: UserDisplayName) =
      encoder.encodeString(value.inner)

    override fun deserialize(decoder: Decoder): UserDisplayName =
      UserDisplayName(decoder.decodeString())
  }
}
