# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in hello_rb.gemspec
gemspec

gem 'irb', '~> 1.3.3', group: :development
gem 'ruby-debug-ide', '~> 0.7.2', group: :development
