# frozen_string_literal: true

source 'https://rubygems.org'

# Load gem's dependencies from etwin.gemspec
gemspec

gem 'irb', '~> 1.3.3', group: :development
gem 'ruby-debug-ide', '~> 0.7.2', group: :development
