// Auto-generated by `xtask dns`, do not edit manually.
export default [
  {domain: "dinorpg.de.", type: "A" as const, target: "178.32.123.64"},
  {domain: "hammerfest.es.", type: "A" as const, target: "149.202.174.50"},
  {domain: "mush.twinoid.es.", type: "A" as const, target: "178.32.123.64"},
];
