// WARNING: DO NOT EDIT THE FILE MANUALLY!
// This file was auto-generated by `cargo xtask kotlin` from the definitions in `xtask/src/metagen/etwin.rs`.

package net.eternaltwin.dinoparc

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

@Serializable(with = DinoparcEpicRewardKey.Serializer::class)
data class DinoparcEpicRewardKey(
  val inner: String,
) {
  fun toDebugString(): String = "DinoparcEpicRewardKey(${this})"

  override fun toString(): String = this.inner

  object Serializer : KSerializer<DinoparcEpicRewardKey> {
    override val descriptor: SerialDescriptor =
      PrimitiveSerialDescriptor("net.eternaltwin.dinoparc.DinoparcEpicRewardKey", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: DinoparcEpicRewardKey) =
      encoder.encodeString(value.inner)

    override fun deserialize(decoder: Decoder): DinoparcEpicRewardKey =
      DinoparcEpicRewardKey(decoder.decodeString())
  }
}
