// WARNING: DO NOT EDIT THE FILE MANUALLY!
// This file was auto-generated by `cargo xtask kotlin` from the definitions in `xtask/src/metagen/etwin.rs`.

package net.eternaltwin.dinoparc

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

@Serializable(with = DinoparcDinozLife.Serializer::class)
data class DinoparcDinozLife(
  val inner: UByte,
) {
  fun toByte(): Byte = this.inner.toByte()
  fun toShort(): Short = this.inner.toShort()
  fun toInt(): Int = this.inner.toInt()
  fun toLong(): Long = this.inner.toLong()
  fun toUByte(): UByte = this.inner
  fun toUShort(): UShort = this.inner.toUShort()
  fun toUInt(): UInt = this.inner.toUInt()
  fun toULong(): ULong = this.inner.toULong()

  companion object {
    @JvmStatic
    fun fromByte(value: Byte): DinoparcDinozLife = DinoparcDinozLife(value.toUByte())
    @JvmStatic
    fun fromShort(value: Short): DinoparcDinozLife = DinoparcDinozLife(value.toUByte())
    @JvmStatic
    fun fromInt(value: Int): DinoparcDinozLife = DinoparcDinozLife(value.toUByte())
    @JvmStatic
    fun fromLong(value: Long): DinoparcDinozLife = DinoparcDinozLife(value.toUByte())
    @JvmStatic
    fun fromUByte(value: UByte): DinoparcDinozLife = DinoparcDinozLife(value)
    @JvmStatic
    fun fromUShort(value: UShort): DinoparcDinozLife = DinoparcDinozLife(value.toUByte())
    @JvmStatic
    fun fromUInt(value: UInt): DinoparcDinozLife = DinoparcDinozLife(value.toUByte())
    @JvmStatic
    fun fromULong(value: ULong): DinoparcDinozLife = DinoparcDinozLife(value.toUByte())
  }

  fun toDebugString(): String = "DinoparcDinozLife(${this})"

  override fun toString(): String = this.inner.toString()

  object Serializer : KSerializer<DinoparcDinozLife> {
    override val descriptor: SerialDescriptor =
      PrimitiveSerialDescriptor("net.eternaltwin.dinoparc.DinoparcDinozLife", PrimitiveKind.LONG)

    override fun serialize(encoder: Encoder, value: DinoparcDinozLife) =
      encoder.encodeLong(value.inner.toLong())

    override fun deserialize(decoder: Decoder): DinoparcDinozLife =
      fromLong(decoder.decodeLong())
  }
}
