// WARNING: DO NOT EDIT THE FILE MANUALLY!
// This file was auto-generated by `cargo xtask kotlin` from the definitions in `xtask/src/metagen/etwin.rs`.

package net.eternaltwin.dinoparc

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

@Serializable(with = DinoparcDinozDanger.Serializer::class)
data class DinoparcDinozDanger(
  val inner: Short,
) {
  constructor(value: Byte): this(value.toShort())
  fun toByte(): Byte = this.inner.toByte()
  fun toShort(): Short = this.inner
  fun toInt(): Int = this.inner.toInt()
  fun toLong(): Long = this.inner.toLong()
  fun toUByte(): UByte = this.inner.toUByte()
  fun toUShort(): UShort = this.inner.toUShort()
  fun toUInt(): UInt = this.inner.toUInt()
  fun toULong(): ULong = this.inner.toULong()

  companion object {
    @JvmStatic
    fun fromByte(value: Byte): DinoparcDinozDanger = DinoparcDinozDanger(value.toShort())
    @JvmStatic
    fun fromShort(value: Short): DinoparcDinozDanger = DinoparcDinozDanger(value)
    @JvmStatic
    fun fromInt(value: Int): DinoparcDinozDanger = DinoparcDinozDanger(value.toShort())
    @JvmStatic
    fun fromLong(value: Long): DinoparcDinozDanger = DinoparcDinozDanger(value.toShort())
    @JvmStatic
    fun fromUByte(value: UByte): DinoparcDinozDanger = DinoparcDinozDanger(value.toShort())
    @JvmStatic
    fun fromUShort(value: UShort): DinoparcDinozDanger = DinoparcDinozDanger(value.toShort())
    @JvmStatic
    fun fromUInt(value: UInt): DinoparcDinozDanger = DinoparcDinozDanger(value.toShort())
    @JvmStatic
    fun fromULong(value: ULong): DinoparcDinozDanger = DinoparcDinozDanger(value.toShort())
  }

  fun toDebugString(): String = "DinoparcDinozDanger(${this})"

  override fun toString(): String = this.inner.toString()

  object Serializer : KSerializer<DinoparcDinozDanger> {
    override val descriptor: SerialDescriptor =
      PrimitiveSerialDescriptor("net.eternaltwin.dinoparc.DinoparcDinozDanger", PrimitiveKind.LONG)

    override fun serialize(encoder: Encoder, value: DinoparcDinozDanger) =
      encoder.encodeLong(value.inner.toLong())

    override fun deserialize(decoder: Decoder): DinoparcDinozDanger =
      fromLong(decoder.decodeLong())
  }
}
