// WARNING: DO NOT EDIT THE FILE MANUALLY!
// This file was auto-generated by `cargo xtask kotlin` from the definitions in `xtask/src/metagen/etwin.rs`.

package net.eternaltwin.dinoparc

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

@Serializable(with = DinoparcUserId.Serializer::class)
data class DinoparcUserId(
  val inner: String,
) {
  fun toDebugString(): String = "DinoparcUserId(${this})"

  override fun toString(): String = this.inner

  object Serializer : KSerializer<DinoparcUserId> {
    override val descriptor: SerialDescriptor =
      PrimitiveSerialDescriptor("net.eternaltwin.dinoparc.DinoparcUserId", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: DinoparcUserId) =
      encoder.encodeString(value.inner)

    override fun deserialize(decoder: Decoder): DinoparcUserId =
      DinoparcUserId(decoder.decodeString())
  }
}
