/**
 * List of routes corresponding to pages (not assets).
 */
export const ROUTES: readonly string[] = [
  "/",
  "/archive",
  "/archive/dinoparc",
  "/archive/dinoparc/:server/users/:user_id",
  "/archive/dinoparc/:server/dinoz/:dinoz_id",
  "/archive/hammerfest",
  "/archive/hammerfest/:server/users/:user_id",
  "/archive/twinoid",
  "/archive/twinoid/users/:user_id",
  "/docs",
  "/docs/:a",
  "/docs/:a/:b",
  "/docs/:a/:b/:c",
  "/docs/:a/:b/:c/:d",
  "/docs/:a/:b/:c/:d/:e",
  "/donate",
  "/forum",
  "/forum/sections/:section_id",
  "/forum/sections/:section_id/new",
  "/forum/threads/:thread_id",
  "/forum/threads/:thread_id/reply",
  "/games",
  "/legal",
  "/login",
  "/register",
  "/register/email",
  "/register/username",
  "/settings",
  "/users/:user_id"
];
